### ISSUE TITLE
Support Swift Version

### ISSUE THREAD

**Issue by kwyeelove** [flowplayer/flowplayer-ios-sdk-demo#2]
What version of Swift do you support?
After 5.1 ? not 5.0 ?

/flowplayer-ios-sdk-demo-master/test/flowplayer-demo/MainViewController.swift:9:8: 
Module compiled with Swift 5.1 cannot be imported by the Swift 5.0.1 compiler: 

/flowplayer-ios-sdk-demo-master/test/Pods/FlowplayerCore/Release-FlowplayerCore/Release-universal/FlowplayerCore.framework/Modules/FlowplayerCore.swiftmodule/x86_64.swiftmodule

**Comment by okkonen** [comment]
We support Swift 5.1. It's default in Xcode 11, which no longer support 5.0.

https://docs.swift.org/swift-book/GuidedTour/Compatibility.html
