### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AtifNaveed** [flowplayer/flowplayer-ios-sdk-demo#3]
Both swift and objc demo crash on add as subview line. There is no detail on crash on console! 

Steps: 
I update pod and replaced access token and compile code but does not work. I tried both simulator and device but no luck. 
Im using xcode 11. 
Any advise?

**Comment by bbbo** [comment]
Just to make sure: you did add the subview *before* calling `flowplayerViewController.prepare`()` ?

**Comment by AtifNaveed** [comment]
Yes, I tried following your documentation/steps form your website, after failing, I started using your demo code on git as it is without any change, I just replace access code in plist to keep it simple. 

The crash is on line number 31
The attached screenshot may help.

<img width="1359" alt="Screenshot 2020-06-15 at 9 27 02 pm" src="https://user-images.githubusercontent.com/5243922/84688193-fbccc680-af4f-11ea-9b0e-5bc9238e3fa9.png">

If you need my machine access or screen share session, I am ok to contribute.

Thanks

**Comment by gsavvid** [comment]
Hi @AtifNaveed! Thank you for reporting this issue and apologies that it took a bit to reply.

Looking closer to your screenshot I noticed that the `containerView` outlet is not referenced by the actual view. I don't know why this happens but it looks like some Xcode issue. In my case, after downloading the demo to my computer everything was referenced properly. However, I managed to reproduce the issue by manually removing this reference.

Could you please try the following steps and let me know if this solves the problem? I've highlighted with red boxes the points of interest.

**Step 1**
First, open `Main.storyboard`. In the `Player View Controller` select the black `View` and verify that its `Referencing Outlets` look like the screenshot below. If that's the case indeed, then we've found the issue.

<img width="950" alt="step1" src="https://user-images.githubusercontent.com/5520133/84868751-77786180-b07d-11ea-9c07-83cdb2712c2d.png">

**Step 2**
Click on the circle to the right of `New Referencing Outlet` and without releasing your mouse click, drag and drop it on the `Player View Controller`.
<img width="950" alt="step2" src="https://user-images.githubusercontent.com/5520133/84868757-78a98e80-b07d-11ea-810b-6ac37a4316e2.png">

**Step 3**
Select `containerView` from the popup.
<img width="950" alt="step3" src="https://user-images.githubusercontent.com/5520133/84868762-79dabb80-b07d-11ea-9c7c-d4a684ff5fd5.png">

**Step 4**
Now you should see the newly referenced outlet.
<img width="950" alt="step4" src="https://user-images.githubusercontent.com/5520133/84868765-7a735200-b07d-11ea-84b0-2de0f000c52f.png">

**Step 5**
And, finally, if you open again `PlayerViewController.swift`, the circle to the left of `containerView` should be filled.
<img width="950" alt="step5" src="https://user-images.githubusercontent.com/5520133/84868766-7b0be880-b07d-11ea-9e56-d52cf6624bd4.png">

**Comment by AtifNaveed** [comment]
@gsavvid that's xCode bug, sometimes it shows empty outlet reference, I am afraid that's not the problem. If we open storyboard and come back to class again it fills automatically. 

**In short:** Its already connected, PFA.

<img width="1348" alt="Screenshot 2020-06-17 at 3 48 47 pm" src="https://user-images.githubusercontent.com/5243922/84894587-16b74c00-b0b2-11ea-9aa6-e966d3cf68a7.png">

**Comment by AtifNaveed** [comment]
@gsavvid problem seems with FPFlowplayerViewController() or flowplayerViewController.view

If you wish we could have a screen share session on my machine.

**Comment by ParasMahadev** [comment]
I have also Similar issue while adding flowplayer.

**Comment by ParasMahadev** [comment]
![Uploading Screenshot 2020-11-22 at 5.32.24 PM.png…]()

**Comment by ParasMahadev** [comment]
I have also Similar issue while adding flowplayer.

<img width="1070" alt="Screenshot 2020-11-22 at 5 32 24 PM" src="https://user-images.githubusercontent.com/3158666/99900083-d4410d80-2ce8-11eb-9512-5e64167039a6.png">
