### ISSUE TITLE
Demo Token

### ISSUE THREAD

**Issue by rincewac** [flowplayer/flowplayer-ios-sdk-demo#4]
Is it possible to get a demo token for checking the functionality of the player ?.

**Comment by bbbo** [comment]
You can subscribe to a 14 day trail at https://flowplayer.com/pricing and then create a token as explained in https://flowplayer.com/help/players/player-tokens

**Comment by rincewac** [comment]
Without giving the card details, is it possible to test ?.

**Comment by JDevlin88** [comment]
@rincewac if you can pass your email address through this form stating that you are looking for an enterprise trial. I can set up a test account for you without having to input card details at this point. 
https://flowplayer.com/contact

**Comment by rincewac** [comment]
@JDevlin88 I have sent. Kindly do it ASAP. Thanks....
