### ISSUE TITLE
Unsupported for Swift 5.4.2

### ISSUE THREAD

**Issue by mazmik25** [flowplayer/flowplayer-ios-sdk-demo#8]
I just add `FlowplayerCore` into my project. After installing and running the app, I got an issue that it's not supported for Swift 5.4.2. 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/25825451/132060845-358aef8a-c9e3-4732-aad2-2b62120a8eea.png">

Here's my `Podfile`

```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'mobile-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for mobile-iOS
    pod 'FlowplayerCore'
    pod 'Rollbar'
    pod 'GoogleAds-IMA-iOS-SDK'
end
```

Can you guys help me to fix this issue? 

Thank you in advance

**Comment by bbbo** [comment]
Hi,

we will release a completely revamped iOS SDK with XCF frameworks and up-to-date Xcode / Swift support early next week.

If you email us from your flowplayer.com customer account, we can put you on the notification list so you'll be informed when it's released.

**Comment by mazmik25** [comment]
Thank you for the quick follow up. I would wait for the next release

**Comment by mazmik25** [comment]
Hi @bbbo ,
thank you for the quick update. I would wait for the next release

Thank you
