### ISSUE TITLE
The audio doesn't come out

### ISSUE THREAD

**Issue by mazmik25** [flowplayer/flowplayer-ios-sdk-demo#9]
I'm currently using the latest version of FlowPlayer.

Here's my cocoapods
```
pod 'Flowplayer'
pod 'Rollbar'
pod 'GoogleAds-IMA-iOS-SDK'
```

And here's how I implement it
```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    containerView.subviews.forEach { $0.removeFromSuperview() }
        let config = FPPlayerControlConfigBuilder()
            .setVolumeControl(true)
            .setControlsVisible(true)
            .setFullscreenControl(false)
            .build()
    flowPlayerViewController.setControlConfig(config)
    containerView.addSubview(flowPlayerViewController.view)
    flowPlayerViewController.addPlayerDelegate(self)
}
```

Is there anything that I missed?

**Comment by mazmik25** [comment]
these are 2 videos that show the case

https://user-images.githubusercontent.com/25825451/138933557-4754b019-6552-4499-a64e-7cfc594894c8.mp4

https://user-images.githubusercontent.com/25825451/138933629-954a8d3c-c225-49d2-829d-1baafc59baab.mp4

**Comment by bbbo** [comment]
Thanks for the report; the dev team is looking into it.

**Comment by br3akzero** [comment]
Hi @mazmik25, 
We have looked into your bug report about the Audio. A new version 2.0.2 for `pod 'Flowplayer'` has been release and will be available in the next couple of hours via CocoaPods. Make sure to run `pod repo update` before updating the Flowplayer pod.

If you have integrated the SDK manually you can downloaded the release using the release page of Flowplayer SDK. 
https://github.com/flowplayer/flowplayer-ios-sdk-public/releases/tag/2.0.2

If the issue has not been fixed for you, feel free to leave a comment.

**Comment by mazmik25** [comment]
Ok. I'll try it and give it the updates

**Comment by mazmik25** [comment]
@Denpex it seems that the version hasn't updated in cocoapods. I've tried to do `pod repo update` and the version remains `2.0.1`

Here's my `Podfile.lock`
<img width="480" alt="Screen Shot 2021-10-29 at 06 58 18" src="https://user-images.githubusercontent.com/25825451/139351903-996c77ca-2ba0-4775-810d-bdc2ee4bca7c.png">

In cocoapods
<img width="480" alt="Screen Shot 2021-10-29 at 06 59 28" src="https://user-images.githubusercontent.com/25825451/139351976-74aa3636-63a2-4a8e-a802-31ed9fcfaf1e.png">

**Comment by br3akzero** [comment]
Hi @mazmik25, It should be online. Please do the following to make sure that CocoaPods updates the pods. 

`pod repo update # This will fetch the new CocoaPods from Master`
`pod update # This will update your current pods` 

If this step doesn't update Flowplayer, please do the following: 

In you Podfile set the minimum version to 2.0.2
`pod 'Flowplayer', '~> 2.0.2`

Then in terminal 
`pod repo update`
`pod update`

**Comment by br3akzero** [comment]
<img width="762" alt="Screen Shot 2021-10-29 at 09 43 02" src="https://user-images.githubusercontent.com/28106084/139396749-8ae27d3f-db16-4b31-b3cf-e787ea242195.png">

**Comment by mazmik25** [comment]
After set the minimum, I could install the latest version. I will give the update soon about the issue. Thank you @Denpex

**Comment by mazmik25** [comment]
I used the latest version, 2.0.2. It works in iOS 15. However, when it's tested on iOS 14.3 and 14.8, the audio still didn't come out. Any other configurations that I missed?
@Denpex @bbbo

**Comment by br3akzero** [comment]
@mazmik25  are you using the SDK with Swift or Objective-C  and does the same issue happen on both simulator and physical device?

**Comment by mazmik25** [comment]
Hi @Denpex 
I'm using Swift and the audio issue only occurs in physical device. Specifically iPhone X OS 14.3 and iPhone 11 OS 14.8. One of my tester was using iPhone 11 OS 14.8 and got the issue. After he updated the OS to 15, the audio started to come out

**Comment by br3akzero** [comment]
Hi @mazmik25, 

Thanks for the detailed feedback,  you are probably missing: 

`try! AVAudioSession.sharedInstance().setCategory(.playback)`

Add this line to `viewDidLoad` before using Flowplayer or in your `AppDelegate` on app startup. This will tell iOS that your app uses Audio playback that is crucial for your app also make sure the volume is on :D.  We do not set this global variable inside of the SDK as it's the client's app responsibility to handle different types of permissions. 

The swift demo app of Flowplayer also has been updated and refactored to showcase this thanks to your feedback.  There is also a new version of Flowplayer out 2.0.3, this is just a minor patch version.

**Comment by mazmik25** [comment]
Hi @Denpex 
I'll try the recommendation and give you the feedback ASAP. Thanks for your help!

**Comment by mazmik25** [comment]
Hi, just want to give you the updates. It is now fixed. Thank you!
